name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'true'
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install blockly dependencies
      working-directory: ./blockly-games
      run: |
        sudo apt-get install unzip subversion default-jre python-is-python3
        make deps
    - name: Build pond app
      working-directory: ./blockly-games
      run: |
        rm -r ./appengine/pond
        ln -nsf $(realpath ../pond) $(realpath ./appengine/pond)
        echo Content of pond:
        ls -lh ./appengine/pond
        make pond-duck-en
        make pond-docs-en
    - name: Deploy pond app
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "pond/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.POND_APP }}
        EXCLUDE: "/dist/, /node_modules/"
    - name: Build tournament app
      working-directory: ./blockly-games
      run: |
        rm -r ./appengine/pond
        ln -nsf $(realpath ../tournament) $(realpath ./appengine/pond)
        make pond-duck-en
    - name: Deploy tournament app
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "tournament/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.TOURNAMENT_APP }}
        EXCLUDE: "/dist/, /node_modules/"
    - name: Deploy tournament-server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "tournament-server/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.TOURNAMENT_SERVER }}
        EXCLUDE: "bots/, node_modules/"
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.OPENSSH_KEY }}
        port: 22
        script: |
          (bash ~/duckdns/duck.sh)
          (cd /root/blockly-games-pond-multiplayer/tournament-server/ && npm install)
          systemctl restart pond
